export const SEARCH_FORM_SUBMIT = 'SEARCH_FORM_SUBMIT';
export const SEARCH_FORM_SUBMIT_SUCCESS = 'SEARCH_FORM_SUBMIT_SUCCESS';
export const SEARCH_FORM_SUBMIT_FAILURE = 'SEARCH_FORM_SUBMIT_FAILURE';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const CARD_MOUSE_ENTER = 'CARD_MOUSE_ENTER';
export const CARD_MOUSE_EXIT = 'CARD_MOUSE_EXIT';
